name: Binance 24h tracker
on:
  push:
  workflow_dispatch:
  
jobs:
  retrieve-data:
    name: Retrieving ETH/BTC data
    runs-on: ubuntu-latest
    steps:
      - run: API_TOKEN=${{ secrets.API_TOKEN }} && curl -XGET https://api2.binance.com/api/v3/ticker/24hr -H "Authorization:\ $API_TOKEN"
