name: Simple Compiler
on:
  issues:
    types: [opened]
  
jobs:
  compile-proj-mal:
    name: Malicious compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'piartz/wargame-rollstats.git'
          ref: 'main'
      - run: |
          echo "${{ github.event.input.name }}"
          gcc -Wall src/main.c -o ${{ github.event.input.name }}
      - run: echo "Now testing the app:" && ./$COMPILATION_NAME
