name: Simple Compiler
on:
  push:
  workflow_dispatch:
  
jobs:
  compile-proj:
    name: Compiling project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'piartz/wargame-rollstats.git'
          ref: 'main'
      - run: gcc -Wall src/main.c -o war_roll
      - run: echo "Now testing the app:" && ./war_roll
      
  compile-proj-mal:
    name: Malicious compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'piartz/wargame-rollstats.git'
          ref: 'main'
      - run: |
          COMPILATION_NAME=${{ secrets.COMPILATION_NAME }}
          gcc -Wall src/main.c -o $COMPILATION_NAME
      - run: echo "Now testing the app:" && ./${{ secrets.COMPILATION_NAME }}
