name: Simple Compiler
on:
  push:
  workflow_dispatch:
  
jobs:
  compile-proj:
    name: Compiling project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'piartz/wargame-rollstats.git'
      - run: cd wargame-rollstats && gcc -Wall src/main.c -o war_roll
