name: Deploy Python server
on:
  workflow_dispatch:
  
jobs:
  deploy-server:
    name: Deploy simple server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Configuring credentials"
          echo
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}
      - run: |
          echo "Initializing Terraform... "
          cd terraform
          terraform init
          terraform apply -auto-approve
      
