name: Deploy Python server
on:
  workflow_dispatch:
  
jobs:
  deploy-server:
    name: Configure AWS credentials
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v3
      - run: |
      echo "Configuring credentials"
      echo
      export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY_ID }}
      export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}
     name: Initialize Terraform
      - run: |
      echo "Initializing Terraform... "
      
