name: Injecting malicious Docker image
on:
  workflow_dispatch:

jobs:
  Run-docker-image:
    name: Run docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v3
        with:
          tags: malicious-image:latest
          context: "{{defaultContext}}:docker-command-injectino"
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: malicious-image:latest
